name: countries
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
    sdk: ">=2.17.0 <3.0.0"

dependencies:
    flutter:
        sdk: flutter
    json_annotation: ^4.4.0

dev_dependencies:
    build_runner: ^2.0.0
    flutter_test:
        sdk: flutter
    json_serializable: ^6.0.0
    lint: ^1.0.0

flutter:
    uses-material-design: true
    assets:
        - assets/countries.json
        - assets/png/
